---
title: "oral_phyloseq"
author: "Erica Ryu"
date: "2/9/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.  Generate Phyloseq Object

The purpose of this script is to process 16S sequences through dada2 and phyloseq, and generate a phyloseq object.

## load packages
```{r}
library(ggplot2)
library(dada2)
library(phyloseq)
library(dplyr)
library(DECIPHER)
library(phangorn)
```

## set variables for loading data
```{r}
set.seed(100)
path = "data/fwd"
filt_path = "data/filt_path"
```

## filter and trim reads
```{r}
fileFwd <- list.files(path, full.names = TRUE)

ii <- sample(length(fileFwd), 3)
for(i in ii) { print(plotQualityProfile(fileFwd[i]) + ggtitle("Fwd")) }

# points to where the filtered files should go
if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFwd <- file.path(filt_path, basename(fileFwd))

out <- filterAndTrim(fileFwd, filtFwd, trimLeft = 10, truncLen=c(150),
              maxN=0, maxEE=2, truncQ=2, compress=TRUE, multithread=TRUE)
```

## infer sequence variants
```{r}
exists <- file.exists(filtFwd)
derepFs <- derepFastq(filtFwd[exists], verbose=TRUE)
sam.names <- sapply(strsplit(basename(fileFwd), ".fastq"), `[`, 1)
names(derepFs) <- sam.names[exists]

ddF <- dada(derepFs[1:40], err=NULL, selfConsist=TRUE)

pdf("output/ErrorRates_ddf.pdf", width=6, height=6)
plotErrors(ddF)
dev.off()

dadaFs <- dada(derepFs, err=ddF[[1]]$err_out, pool=TRUE)
```

## construct sequence table
```{r}
seqtab.all <- makeSequenceTable(dadaFs)
dim(seqtab.all) 

sum(seqtab.all) 
table(nchar(getSequences(seqtab.all)))
```

## remove chimeras
```{r}
seqtab <- removeBimeraDenovo(seqtab.all)
dim(seqtab)

sum(seqtab) 

sum(seqtab)/sum(seqtab.all)
table(nchar(getSequences(seqtab)))
```

## track reads
```{r}
# filter out the samples that did not pass filtering
samples_remove <- c("RAJ0019YZ_genotek.fastq", "THA0065JZ_genotek.fastq")
out_subsetted <- out[!(rownames(out) %in% samples_remove), ]
samples_remove_names <- c("RAJ0019YZ_genotek", "THA0065JZ_genotek")
sam.names_subsetted <- sam.names[!(sam.names %in% samples_remove_names)]

getN <- function(x) sum(getUniques(x))
track <- cbind(out_subsetted, sapply(dadaFs, getN), rowSums(seqtab))
colnames(track) <- c("input", "filtered", "denoisedF", "nochim")
rownames(track) <- sam.names_subsetted
track <- as.data.frame(track)
track$retained_overall <- track$nochim / track$input

# save read track table
write.csv(track, file = "output/track_reads.csv")
```

## assign taxonomy
```{r}
ref_fasta <- tempfile()
download.file("http://benjjneb.github.io/dada2/rdp_train_set_14.fa.gz", destfile = ref_fasta)
taxtab <- assignTaxonomy(seqtab, refFasta = ref_fasta)
colnames(taxtab) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")
```

## construct phylogenetic tree
```{r}
seqs <- getSequences(seqtab)
names(seqs) <- seqs

alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)

phang.align <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phang.align)
treeNJ <- NJ(dm) 
fit = pml(treeNJ, data=phang.align)


fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                    rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)
```

## construct phyloseq object
```{r}
# load in metadata
map<-read.csv("data/s1_tab_surveydata.csv")

head(map)
map<-data.frame(map)

# construct object
map <- map[!duplicated(map$SampleID),] 
all(rownames(seqtab) %in% map$SampleID) # check if TRUE

#If false, run the lines below to remove sequences without meta data and metadata without sequences
seqtab[(rownames(seqtab) %in% map$SampleID),]->seqtab
map[(map$SampleID %in% rownames(seqtab)),]->map
#this should now be TRUE
all(rownames(seqtab) %in% map$SampleID)

rownames(map) <- map$SampleID
keep.cols=names(map)
samdf <- map[rownames(seqtab), keep.cols]
ps <- phyloseq(tax_table(taxtab), 
               sample_data(samdf), 
               otu_table(seqtab, taxa_are_rows = FALSE),
               phy_tree(fitGTR$tree)
)
ps

# save phyloseq object
saveRDS(ps, "output/oralmicrobiome_ps.rds")
```

